<div id="TAG"></div>

<div id="GET"></div>

<!-- /********************************************/ -->

<footer>

    <!-- /************** * GRAPHIC TEMP SCRIPTS * **************/ -->

		<script src="<?php echo $js; ?>feather.min.js" type="text/javascript"></script>

		<script src="<?php echo $js; ?>jquery-3.5.1.js" type="text/javascript"></script>

	  <script src="<?php echo $js; ?>jquery-ui.min.js" type="text/javascript"></script>
	  <script src="<?php echo $js; ?>popper.min.js" type="text/javascript"></script>

		<script src="<?php echo $js; ?>jquery-3.4.1-mask.main.js" type="text/javascript"></script>

		<script src="<?php echo $js; ?>jquery.form.min.js"></script>

		<!-- Page level plugins -->
	  <script src="<?php echo $js; ?>jquery.dataTables.min.js"></script>
    <script src="<?php echo $js; ?>bootstrap.min.js"></script>
		<script src="<?php echo $js; ?>dataTables.bootstrap4.min.js"></script>
		<script src="<?php echo $js; ?>dataTables.responsive.min.js"></script>
		<script src="<?php echo $js; ?>responsive.bootstrap4.min.js"></script>
		<script src="<?php echo $js ?>swal.js"></script>

		<script src="<?php echo $live; ?>AJAX.js" type="text/javascript"></script>
    <script src="<?php echo $js; ?>js.js" type="text/javascript"></script>

</footer>

  </body>
</html>
